spring:
  application:
    name: movie_review_java_25
  datasource:
    url: jdbc:h2:./db/movie_review;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  #  sql:
  #    init:
  #      mode: always

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  mvc:
    static-path-pattern: /static/**
    log-request-details: false
  freemarker:
    expose-session-attributes: true


server:
  port: 8089


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    path: logs